const r = require('express').Router();
const c = require('../controllers/user.controller');
const { protect } = require('../middleware/auth');
const asyncHandler = require('../middleware/asyncHandler');
r.use(protect);
r.get('/', asyncHandler(c.list));
r.get('/:id', asyncHandler(c.get));
r.post('/', asyncHandler(c.create));
r.put('/:id', asyncHandler(c.update));
r.patch('/:id/status', asyncHandler(c.setStatus));
r.post('/:id/reset-password', asyncHandler(c.resetPassword));
r.delete('/:id', asyncHandler(c.remove));
module.exports = r;